/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "sigs.k8s.io/work-api/pkg/apis/v1alpha1"
)

// AppliedWorkLister helps list AppliedWorks.
// All objects returned here must be treated as read-only.
type AppliedWorkLister interface {
	// List lists all AppliedWorks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AppliedWork, err error)
	// AppliedWorks returns an object that can list and get AppliedWorks.
	AppliedWorks(namespace string) AppliedWorkNamespaceLister
	AppliedWorkListerExpansion
}

// appliedWorkLister implements the AppliedWorkLister interface.
type appliedWorkLister struct {
	indexer cache.Indexer
}

// NewAppliedWorkLister returns a new AppliedWorkLister.
func NewAppliedWorkLister(indexer cache.Indexer) AppliedWorkLister {
	return &appliedWorkLister{indexer: indexer}
}

// List lists all AppliedWorks in the indexer.
func (s *appliedWorkLister) List(selector labels.Selector) (ret []*v1alpha1.AppliedWork, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AppliedWork))
	})
	return ret, err
}

// AppliedWorks returns an object that can list and get AppliedWorks.
func (s *appliedWorkLister) AppliedWorks(namespace string) AppliedWorkNamespaceLister {
	return appliedWorkNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AppliedWorkNamespaceLister helps list and get AppliedWorks.
// All objects returned here must be treated as read-only.
type AppliedWorkNamespaceLister interface {
	// List lists all AppliedWorks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AppliedWork, err error)
	// Get retrieves the AppliedWork from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AppliedWork, error)
	AppliedWorkNamespaceListerExpansion
}

// appliedWorkNamespaceLister implements the AppliedWorkNamespaceLister
// interface.
type appliedWorkNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AppliedWorks in the indexer for a given namespace.
func (s appliedWorkNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AppliedWork, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AppliedWork))
	})
	return ret, err
}

// Get retrieves the AppliedWork from the indexer for a given namespace and name.
func (s appliedWorkNamespaceLister) Get(name string) (*v1alpha1.AppliedWork, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("appliedwork"), name)
	}
	return obj.(*v1alpha1.AppliedWork), nil
}
