/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/work-api/pkg/apis/v1alpha1"
	scheme "sigs.k8s.io/work-api/pkg/client/clientset/versioned/scheme"
)

// AppliedWorksGetter has a method to return a AppliedWorkInterface.
// A group's client should implement this interface.
type AppliedWorksGetter interface {
	AppliedWorks() AppliedWorkInterface
}

// AppliedWorkInterface has methods to work with AppliedWork resources.
type AppliedWorkInterface interface {
	Create(ctx context.Context, appliedWork *v1alpha1.AppliedWork, opts v1.CreateOptions) (*v1alpha1.AppliedWork, error)
	Update(ctx context.Context, appliedWork *v1alpha1.AppliedWork, opts v1.UpdateOptions) (*v1alpha1.AppliedWork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, appliedWork *v1alpha1.AppliedWork, opts v1.UpdateOptions) (*v1alpha1.AppliedWork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AppliedWork, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AppliedWorkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AppliedWork, err error)
	AppliedWorkExpansion
}

// appliedWorks implements AppliedWorkInterface
type appliedWorks struct {
	*gentype.ClientWithList[*v1alpha1.AppliedWork, *v1alpha1.AppliedWorkList]
}

// newAppliedWorks returns a AppliedWorks
func newAppliedWorks(c *MulticlusterV1alpha1Client) *appliedWorks {
	return &appliedWorks{
		gentype.NewClientWithList[*v1alpha1.AppliedWork, *v1alpha1.AppliedWorkList](
			"appliedworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.AppliedWork { return &v1alpha1.AppliedWork{} },
			func() *v1alpha1.AppliedWorkList { return &v1alpha1.AppliedWorkList{} }),
	}
}
